### ISSUE TITLE
More permissive License

### ISSUE THREAD

**Issue by godofdream** [angelhodar/OpenRPG_Inventory#1]
I like your project and i would like to include your rpg inventory into my game. Your license is however gpl. Would you consider to switch the license to something more permissive? MIT or LGPL?

**Comment by angelhodar** [comment]
@godofdream First of all sorry for not getting notified about you issue. You can use the project for anything you want, I just added that license because is the one I am used to. Glad you liked the project!!

**Comment by daniel-eder** [comment]
@angelhodar If I may chime in on this, by not specifying any license this project arguably is no longer open-source, but rather protected fully by copyright, effectively preventing anyone from using it. 

Based on your statement above you intend to make the project as openly usable as possible - in this case, a permissive license like the [MIT license](https://opensource.org/licenses/MIT) (simply put: use for anything as long as you give credits) would offer itself. To allow even more freedom you could apply the [CC0 1.0](https://creativecommons.org/publicdomain/zero/1.0/), which, in all jurisdictions that allow this, put your work in the public domain, removing even the need for attribution. 

As this looks like a cool project and good resource for Unreal Engine so it would be sad to see a reduced adoption due to a lack of legal clarity. If you would like further information on license choices and their effects let me know :)

**Comment by angelhodar** [comment]
Hey @daniel-eder thank you for taking your time and your opinion about this project ;) My knowledge about licenses are very limited, so I just add the GPL license to all my projects by default. I received an email telling me to change the license or removing it, so I decided to remove the LICENSE file from all my OpenRPG repos, but as you say that is even worse now because it means that I am preventing anyone for using it.

As I understand in your comment, I should just add the MIT LICENSE to the project and that should fix all the problems right? I would like the people using this system to mention me in the credits, so that would be the best license as your say. Am I correct?

Thank you for your time ;)

**Comment by daniel-eder** [comment]
Hi @angelhodar, glad I can be of assistance, it would indeed be a shame if the full potential of this (or any of your projects) cannot be reached because of the choice of licenses - which can be quite confusing at times. 

Indeed adding the MIT license fixes all these problems, and ensures that you are credited for your work as it requires a mention in the copyright notice. Simply add a file named LICENSE or LICENSE.txt into your repository, copy the [MIT license text](https://choosealicense.com/licenses/mit/) and update the text with your desired copyright line. 

In fact, if your desire is that your future projects can be widely used, it is a good idea to stick to so-called "permissive licenses", such as the MIT license, because they make it easier for your creations to be used, from a legal perspective. 
However, if your intention is to make sure anyone who creates a work based on yours also makes it open source, then the GPL or other copyleft licenses are the better choice.

**Comment by angelhodar** [comment]
Thank you so much @daniel-eder now I have included the MIT license in all my projects so that should be everything :)

Licenses apart, are you using this project or any other OpenRPG resource? How did you find it?
